#!/bin/bash

echo "// This file is auto-generated by $0 -- do not edit."
echo "goog.module('soccersubTest');"
echo "goog.setTestOnly('soccersubTest');"
echo ""

modules=""
for file in $*; do
  module=$(grep goog.module "$file" | cut -f2 -d\' | cut -f2 -d.)
  modules="$modules $module"
done
for module in $modules; do
    echo "const $module = goog.require('soccersub.$module');"
done
echo "const TestUtil = goog.require('soccersub.TestUtil');"

echo ""
echo "const soccersubTest = () => {"

# Actually generate references to the required modules in the test JS, for
# two purposes:
#   - easy to notice which test-module failed to load, if any.
#   - compiler will not dead-code-eliminate the test.
for module in $modules; do
    echo "  TestUtil.addTestSuite($module);"
done
echo "  TestUtil.runTestSuite();"
echo "}"
echo ""
echo "goog.exportSymbol('soccersubTest', soccersubTest);"
